[dev_server]
paths = ["Pray.web/src"]
dev_port = 8080

[run]
dev = "bash -c 'cd Pray.web && bun run dev'"
build = "bash -c 'cd Pray.web && bun run build:love'"
"build:dev" = "bash -c 'cd Pray.web && bun run build:dev:love'"
