[dev_server]
paths = ["Pray.web/src"]
dev_port = 8080

[run]
dev = "bash -c 'cd Pray.web && npm run dev'"
build = "bash -c 'cd Pray.web && npm run build:all:love'"
"build:dev" = "bash -c 'cd Pray.web && npm run build:all:dev:love'"
