using System.Text.Json;
using System.Text.Json.Serialization;
using PrayAdFree.Core.Services;

var repoRoot = FindRepoRoot(AppContext.BaseDirectory);
var outputDir = Path.Combine(repoRoot, "Pray.web", "src", "generated");
Directory.CreateDirectory(outputDir);

var options = new JsonSerializerOptions {
    WriteIndented = true,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
};

var contract = WebContractExporter.Export();
var json = JsonSerializer.Serialize(contract, options);
var jsonPath = Path.Combine(outputDir, "core-contract.json");
var tsPath = Path.Combine(outputDir, "core-contract.ts");

File.WriteAllText(jsonPath, json + Environment.NewLine);
File.WriteAllText(tsPath, BuildTypeScript(json));

Console.WriteLine($"Generated {Path.GetRelativePath(repoRoot, jsonPath)}");
Console.WriteLine($"Generated {Path.GetRelativePath(repoRoot, tsPath)}");

static string FindRepoRoot(string start) {
    var directory = new DirectoryInfo(start);
    while (directory is not null) {
        if (File.Exists(Path.Combine(directory.FullName, "PrayAdFree.slnx"))) {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new InvalidOperationException("Could not locate PrayAdFree repository root.");
}

static string BuildTypeScript(string json) =>
    $$"""
    // Generated by tools/generate-web-contracts. Do not edit by hand.
    // Change PrayAdFree.Core, then run:
    // dotnet run --project tools/generate-web-contracts/GenerateWebContracts.csproj

    export const coreContract = {{json}} as const;

    export type CoreContract = typeof coreContract;
    export type CoreRpcMethod = CoreContract["rpcMethods"][number];
    """;
