<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\PrayAdFree\Resources\Raw\i18n\*.json" Link="Resources\i18n\%(Filename)%(Extension)" LogicalName="PrayAdFree.Core.Resources.i18n.%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
